name: Render Manim Scenes

on:
  push:
    branches:
      - main # 或者你的主分支名称
  pull_request:
    branches:
      - main # 或者你的主分支名称

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9' # Manim 可能需要特定版本的 Python

      - name: Install Manim and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libpango1.0-dev libcairo2-dev libgl1-mesa-dev libglu1-mesa-dev texlive-full
          pip install manim

      - name: Make render script executable
        run: chmod +x render_scenes.sh

      - name: Render all scenes
        run: ./render_scenes.sh

      - name: Upload video artifacts
        uses: actions/upload-artifact@v3
        with:
          name: manim-videos
          path: media/videos/example_scene/480p15/ # Manim 默认输出路径，可能需要根据实际情况调整
          if-no-files-found: error # 如果没有文件则报错
